FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

# Add all NEXT_PUBLIC environment variables
ARG NEXT_PUBLIC_YOUTUBE_API
ARG NEXT_PUBLIC_SPOTIFY_ID
ARG NEXT_PUBLIC_SPOTIFY_SECRET
ARG NEXT_PUBLIC_LASTFM_API_KEY
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_KEY

# Add non-public environment variables
ARG GOOGLE_GEMINI_API_KEY
ARG OPENAI_API_KEY
ARG ANTHROPIC_API_KEY

ENV NEXT_PUBLIC_YOUTUBE_API=$NEXT_PUBLIC_YOUTUBE_API
ENV NEXT_PUBLIC_SPOTIFY_ID=$NEXT_PUBLIC_SPOTIFY_ID
ENV NEXT_PUBLIC_SPOTIFY_SECRET=$NEXT_PUBLIC_SPOTIFY_SECRET
ENV NEXT_PUBLIC_LASTFM_API_KEY=$NEXT_PUBLIC_LASTFM_API_KEY
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_KEY=$NEXT_PUBLIC_SUPABASE_KEY

# Set non-public environment variables
ENV GOOGLE_GEMINI_API_KEY=$GOOGLE_GEMINI_API_KEY
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
ENV LASTFM_API_KEY=$LASTFM_API_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV DATABASE_URL=$DATABASE_URL
ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_KEY=$SUPABASE_KEY

# Add these environment variables before the build
ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_SHARP_PATH=/tmp/node_modules/sharp
ENV OUTPUT_STANDALONE=true

RUN npm install
RUN npx prisma generate

COPY . .

ENV NODE_ENV=production

# Build with specific configuration for handling API routes
# RUN NEXT_BUILD_API_ROUTES=true npm run build

EXPOSE 3000

CMD ["npm", "start"]
